CREATE TABLE IF NOT EXISTS Addresses
(
  country VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  postcode VARCHAR(20) NOT NULL,
  address_id SERIAL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(id)
);